name: indent
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PG: 15

    steps:
      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: '5.34'
      - run: cpanm --installdeps .
      - run: prove -lv t
      
      - name: Initialize the env before installing Postgres
        run: |
          sudo apt-get -y --purge --no-upgrade remove postgresql libpq-dev libpq5 postgresql-client-common postgresql-common
          sudo apt install curl ca-certificates gnupg
          curl https://www.postgresql.org/media/keys/ACCC4CF8.asc | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/apt.postgresql.org.gpg >/dev/null
          sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
          sudo apt-get update -qq
          sudo rm -rf /var/lib/postgresql
      
      - name: Install PostgreSQL & pgindent
        run: |
          sudo apt-get -y \
                -o Dpkg::Options::=--force-confdef \
                -o Dpkg::Options::=--force-confnew \
                install postgresql-${PG:?} postgresql-server-dev-${PG:?} pg-bsd-indent


      - name: Get headers
        run: |
          cd /usr/local/src/postgresql
          sudo wget -O src/tools/pgindent/typedefs.list https://buildfarm.postgresql.org/cgi-bin/typedefs.pl

      - name: Get PerlTidy
        run: |
          wget https://cpan.metacpan.org/authors/id/S/SH/SHANCOCK/Perl-Tidy-20170521.tar.gz
          tar xvfz Perl-Tidy-20170521.tar.gz 
          cd Perl-Tidy-20170521
          perl Makefile.PL 
          make
          make test
          make install
          cd ..
