name: tests
on:
  push:
    branches:
        - master
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    container: pgxn/pgxn-tools
    strategy:
      matrix:
        postgresql-version: [11, 12, 13, 14, 15]

    steps:
      - name: Start PostgreSQL ${{ matrix.pg }}
        run: pg-start ${{ matrix.postgresql-version }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and Test
        run: make && sudo -E make install && time make installcheck

      - name: Show regression diffs
        if: always()
        run: cat regression.diffs || true
