name: tests
on:
  push:
    branches:
        - master
  pull_request:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        postgresql-version: [12, 13, 14, 15]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install PostgreSQL
        env:
          POSTGRESQL_VERSION: ${{ matrix.postgresql-version}}
        run: |
          sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
          wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
          sudo apt-get update
          sudo apt-get -y install "postgresql-$POSTGRESQL_VERSION"
          sudo apt-get -y install "postgresql-server-dev-$POSTGRESQL_VERSION"

      - name: Build
        run: make

      - name: Run tests
        run: sudo make installcheck
